name: music_player
description: A new Flutter plugin.
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0" 

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.1
  system_clock: ^1.2.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: tech.soit.quiet
        pluginClass: MusicPlayerUiPlugin
      ios:
        pluginClass: MusicPlayerUiPlugin
